import type { PermissionContext, PermissionEffect, PermissionScopeType } from './permission.types';

export interface PermissionDefinition {
  key: string;
  category: string;
  module: string;
  displayName: string;
  description: string;
  allowedScopes: PermissionScopeType[];
  allowedContexts: PermissionContext[];
  system: boolean;
}

const workspaceScopes: PermissionScopeType[] = [
  'SELF',
  'ASSIGNED_TRAINEES',
  'SPECIFIC_TRAINEES',
  'BRANCH',
  'MULTIPLE_BRANCHES',
  'WORKSPACE',
];

export const Permissions = {
  PlatformMembershipsRead: 'platform_users.read',
  PlatformMembershipsManage: 'platform_users.manage',
  PlatformPermissionsManage: 'platform_permissions.manage',
  PlatformWorkspacesManage: 'platform_workspaces.manage',
  PlansRead: 'plans.read',
  PlansCreate: 'plans.create',
  PlansUpdate: 'plans.update',
  PlansArchive: 'plans.archive',
  PlansVersionsCreate: 'plans.versions.create',
  SubscriptionsRead: 'subscriptions.read',
  SubscriptionsStartTrial: 'subscriptions.start_trial',
  SubscriptionsChangePlan: 'subscriptions.change_plan',
  SubscriptionsChangeTerms: 'subscriptions.change_terms',
  SubscriptionsFreeze: 'subscriptions.freeze',
  SubscriptionsReactivate: 'subscriptions.reactivate',
  SubscriptionsCancel: 'subscriptions.cancel',
  PaymentsRead: 'payments.read',
  PaymentsApprove: 'payments.approve',
  PaymentsReject: 'payments.reject',
  WorkspacesRead: 'workspace.read',
  WorkspacesManage: 'workspace.manage',
  WorkspacesUpdate: 'workspace.update',
  BillingSubscriptionRead: 'billing.subscription.read',
  BillingUsageRead: 'billing.usage.read',
  BillingPaymentsRead: 'billing.payments.read',
  BillingPaymentsCreate: 'billing.payments.create',
  BranchesRead: 'branches.read',
  BranchesManage: 'branches.manage',
  BranchesCreate: 'branches.create',
  BranchesUpdate: 'branches.update',
  BranchesArchive: 'branches.archive',
  StaffRead: 'staff.read',
  StaffManage: 'staff.manage',
  StaffInvite: 'staff.invite',
  StaffInvitesRevoke: 'staff.invites.revoke',
  StaffBranchesManage: 'staff.branches.manage',
  StaffPermissionsManage: 'staff.permissions.manage',
  TraineesRead: 'trainees.read',
  TraineesUpdate: 'trainees.update',
  TraineesInvite: 'trainees.invite',
  TraineesAccept: 'trainees.accept',
  TraineesReject: 'trainees.reject',
  TraineesEnd: 'trainees.end',
  TraineesReactivate: 'trainees.reactivate',
  TraineesAssignmentsPrimaryManage: 'trainees.assignments.primary.manage',
  TraineesAssignmentsAssistantManage: 'trainees.assignments.assistant.manage',
  TraineesAssignmentsNutritionistManage: 'trainees.assignments.nutritionist.manage',
  TraineesMigrateOut: 'trainees.migrate_out',
  TraineesMigrateIn: 'trainees.migrate_in',
  ExercisesRead: 'exercises.read',
  ExercisesCreate: 'exercises.create',
  ExercisesUpdate: 'exercises.update',
  ExercisesArchive: 'exercises.archive',
  ProgramsRead: 'programs.read',
  ProgramsCreate: 'programs.create',
  ProgramsUpdate: 'programs.update',
  ProgramsActivate: 'programs.activate',
  ProgramsComplete: 'programs.complete',
  ProgramsArchive: 'programs.archive',
  ProgramTemplatesRead: 'program_templates.read',
  ProgramTemplatesCreate: 'program_templates.create',
  ProgramTemplatesUpdate: 'program_templates.update',
  ProgramTemplatesArchive: 'program_templates.archive',
  FoodsRead: 'foods.read',
  FoodsCreate: 'foods.create',
  FoodsUpdate: 'foods.update',
  FoodsArchive: 'foods.archive',
  NutritionPlansRead: 'nutrition.plans.read',
  NutritionPlansCreate: 'nutrition.plans.create',
  NutritionPlansUpdate: 'nutrition.plans.update',
  NutritionPlansActivate: 'nutrition.plans.activate',
  NutritionPlansComplete: 'nutrition.plans.complete',
  NutritionPlansArchive: 'nutrition.plans.archive',
  DocumentsRead: 'documents.read',
  MedicalDocumentsRead: 'medical_documents.read',
  LeadsRead: 'leads.read',
  LeadsUpdate: 'leads.update',
  LeadsConvert: 'leads.convert',
  LeadsMarkDuplicate: 'leads.mark_duplicate',
  LeadsMerge: 'leads.merge',
  SupportSessionsStart: 'support.sessions.start',
  SystemExercisesRead: 'system_exercises.read',
  SystemExercisesCreate: 'system_exercises.create',
  SystemExercisesUpdate: 'system_exercises.update',
  SystemExercisesArchive: 'system_exercises.archive',
  SystemFoodsRead: 'system_foods.read',
  SystemFoodsCreate: 'system_foods.create',
  SystemFoodsUpdate: 'system_foods.update',
  SystemFoodsArchive: 'system_foods.archive',
  WorkoutsRead: 'workouts.read',
  WorkoutsCreate: 'workouts.create',
  WorkoutsUpdate: 'workouts.update',
  WorkoutsComplete: 'workouts.complete',
  WorkoutsAbandon: 'workouts.abandon',
  WorkoutsCorrect: 'workouts.correct',
  WorkoutsDaySkip: 'workouts.day.skip',
  WorkoutsDayDefer: 'workouts.day.defer',
  PersonalRecordsRead: 'personal_records.read',
  MetricDefinitionsRead: 'metric_definitions.read',
  MetricDefinitionsCreate: 'metric_definitions.create',
  MetricDefinitionsUpdate: 'metric_definitions.update',
  MetricDefinitionsArchive: 'metric_definitions.archive',
  MeasurementsRead: 'measurements.read',
  MeasurementsCreate: 'measurements.create',
  MeasurementsUpdate: 'measurements.update',
  ProgressPhotosRead: 'progress_photos.read',
  ProgressPhotosCreate: 'progress_photos.create',
  ProgressPhotosUpdateVisibility: 'progress_photos.update_visibility',
  ProgressPhotosDelete: 'progress_photos.delete',
  HealthRead: 'health.read',
  HealthUpdate: 'health.update',
  HealthFoodAllergiesRead: 'health.food_allergies.read',
  NotesRead: 'notes.read',
  NotesCreate: 'notes.create',
  NotesUpdate: 'notes.update',
  NotesArchive: 'notes.archive',
  AdherenceRead: 'adherence.read',
  AdherenceConfigure: 'adherence.configure',
  AdherenceUpdate: 'adherence.update',
  AdherenceCorrect: 'adherence.correct',
} as const;

export type PermissionKey = (typeof Permissions)[keyof typeof Permissions];

export const permissionDefinitions: PermissionDefinition[] = [
  platform(Permissions.PlatformMembershipsRead, 'Platform users', 'Read Platform memberships.'),
  platform(Permissions.PlatformMembershipsManage, 'Platform users', 'Manage Platform memberships.'),
  platform(
    Permissions.PlatformPermissionsManage,
    'Platform permissions',
    'Manage Platform permission profiles and grants.',
  ),
  platform(
    Permissions.PlatformWorkspacesManage,
    'Platform workspaces',
    'Create and administer workspaces from the Platform context.',
  ),
  platform(Permissions.PlansRead, 'Plans', 'Read subscription plans.'),
  platform(Permissions.PlansCreate, 'Plans', 'Create subscription plans.'),
  platform(Permissions.PlansUpdate, 'Plans', 'Update subscription plan metadata.'),
  platform(Permissions.PlansArchive, 'Plans', 'Archive subscription plans.'),
  platform(Permissions.PlansVersionsCreate, 'Plans', 'Create subscription plan versions.'),
  platform(Permissions.SubscriptionsRead, 'Subscriptions', 'Read workspace subscriptions.'),
  platform(Permissions.SubscriptionsStartTrial, 'Subscriptions', 'Start workspace trials.'),
  platform(Permissions.SubscriptionsChangePlan, 'Subscriptions', 'Change subscription plan terms.'),
  platform(Permissions.SubscriptionsChangeTerms, 'Subscriptions', 'Change subscription terms.'),
  platform(Permissions.SubscriptionsFreeze, 'Subscriptions', 'Freeze workspace subscriptions.'),
  platform(
    Permissions.SubscriptionsReactivate,
    'Subscriptions',
    'Reactivate workspace subscriptions.',
  ),
  platform(Permissions.SubscriptionsCancel, 'Subscriptions', 'Cancel workspace subscriptions.'),
  platform(Permissions.PaymentsRead, 'Payments', 'Read manual payments.'),
  platform(Permissions.PaymentsApprove, 'Payments', 'Approve manual payments.'),
  platform(Permissions.PaymentsReject, 'Payments', 'Reject manual payments.'),
  workspace(Permissions.WorkspacesRead, 'Workspace', 'Read workspace details.'),
  workspace(Permissions.WorkspacesManage, 'Workspace', 'Manage workspace details.'),
  workspace(Permissions.WorkspacesUpdate, 'Workspace', 'Update workspace details.'),
  workspace(Permissions.BillingSubscriptionRead, 'Billing', 'Read workspace subscription state.'),
  workspace(Permissions.BillingUsageRead, 'Billing', 'Read workspace subscription usage.'),
  workspace(Permissions.BillingPaymentsRead, 'Billing', 'Read workspace manual payments.'),
  workspace(Permissions.BillingPaymentsCreate, 'Billing', 'Create workspace manual payments.'),
  workspace(Permissions.BranchesRead, 'Branches', 'Read branches.'),
  workspace(Permissions.BranchesManage, 'Branches', 'Manage branches.'),
  workspace(Permissions.BranchesCreate, 'Branches', 'Create branches.'),
  workspace(Permissions.BranchesUpdate, 'Branches', 'Update branches.'),
  workspace(Permissions.BranchesArchive, 'Branches', 'Archive branches.'),
  workspace(Permissions.StaffRead, 'Staff', 'Read staff memberships.'),
  workspace(Permissions.StaffManage, 'Staff', 'Manage staff memberships.'),
  workspace(Permissions.StaffInvite, 'Staff', 'Invite staff memberships.'),
  workspace(Permissions.StaffInvitesRevoke, 'Staff', 'Revoke staff invitations.'),
  workspace(Permissions.StaffBranchesManage, 'Staff branches', 'Manage staff branch assignments.'),
  workspace(
    Permissions.StaffPermissionsManage,
    'Staff permissions',
    'Manage workspace permission profiles and grants.',
  ),
  workspace(Permissions.TraineesRead, 'Trainees', 'Read trainees.'),
  workspace(Permissions.TraineesUpdate, 'Trainees', 'Update trainee relationship metadata.'),
  workspace(Permissions.TraineesInvite, 'Trainees', 'Invite trainees.'),
  workspace(Permissions.TraineesAccept, 'Trainees', 'Accept pending trainee requests.'),
  workspace(Permissions.TraineesReject, 'Trainees', 'Reject pending trainee requests.'),
  workspace(Permissions.TraineesEnd, 'Trainees', 'End trainee coaching relationships.'),
  workspace(Permissions.TraineesReactivate, 'Trainees', 'Reactivate ended trainee relationships.'),
  workspace(
    Permissions.TraineesAssignmentsPrimaryManage,
    'Trainee assignments',
    'Manage primary trainer assignments.',
  ),
  workspace(
    Permissions.TraineesAssignmentsAssistantManage,
    'Trainee assignments',
    'Manage assistant trainer assignments.',
  ),
  workspace(
    Permissions.TraineesAssignmentsNutritionistManage,
    'Trainee assignments',
    'Manage nutritionist assignments.',
  ),
  workspace(Permissions.TraineesMigrateOut, 'Trainee migrations', 'Migrate trainees out.'),
  workspace(Permissions.TraineesMigrateIn, 'Trainee migrations', 'Migrate trainees in.'),
  workspace(Permissions.ExercisesRead, 'Exercises', 'Read exercise library entries.'),
  workspace(Permissions.ExercisesCreate, 'Exercises', 'Create exercise library entries.'),
  workspace(Permissions.ExercisesUpdate, 'Exercises', 'Update exercise library entries.'),
  workspace(Permissions.ExercisesArchive, 'Exercises', 'Archive exercise library entries.'),
  workspace(Permissions.ProgramsRead, 'Programs', 'Read training programs.'),
  workspace(Permissions.ProgramsCreate, 'Programs', 'Create assigned training programs.'),
  workspace(Permissions.ProgramsUpdate, 'Programs', 'Update training programs.'),
  workspace(Permissions.ProgramsActivate, 'Programs', 'Activate assigned training programs.'),
  workspace(Permissions.ProgramsComplete, 'Programs', 'Complete assigned training programs.'),
  workspace(Permissions.ProgramsArchive, 'Programs', 'Archive assigned training programs.'),
  workspace(Permissions.ProgramTemplatesRead, 'Program templates', 'Read program templates.'),
  workspace(Permissions.ProgramTemplatesCreate, 'Program templates', 'Create program templates.'),
  workspace(Permissions.ProgramTemplatesUpdate, 'Program templates', 'Update program templates.'),
  workspace(Permissions.ProgramTemplatesArchive, 'Program templates', 'Archive program templates.'),
  workspace(Permissions.FoodsRead, 'Foods', 'Read food library entries.'),
  workspace(Permissions.FoodsCreate, 'Foods', 'Create food library entries.'),
  workspace(Permissions.FoodsUpdate, 'Foods', 'Update food library entries.'),
  workspace(Permissions.FoodsArchive, 'Foods', 'Archive food library entries.'),
  workspace(Permissions.WorkoutsRead, 'Workouts', 'Read workout sessions.'),
  workspace(Permissions.WorkoutsCreate, 'Workouts', 'Start workout sessions.'),
  workspace(Permissions.WorkoutsUpdate, 'Workouts', 'Update workout actuals.'),
  workspace(Permissions.WorkoutsComplete, 'Workouts', 'Complete workout sessions.'),
  workspace(Permissions.WorkoutsAbandon, 'Workouts', 'Abandon workout sessions.'),
  workspace(Permissions.WorkoutsCorrect, 'Workouts', 'Correct completed workout sessions.'),
  workspace(Permissions.WorkoutsDaySkip, 'Program progress', 'Skip the current training day.'),
  workspace(Permissions.WorkoutsDayDefer, 'Program progress', 'Defer the current training day.'),
  workspace(Permissions.PersonalRecordsRead, 'Personal records', 'Read personal records.'),
  workspace(Permissions.MetricDefinitionsRead, 'Progress metrics', 'Read metric definitions.'),
  workspace(Permissions.MetricDefinitionsCreate, 'Progress metrics', 'Create metric definitions.'),
  workspace(Permissions.MetricDefinitionsUpdate, 'Progress metrics', 'Update metric definitions.'),
  workspace(
    Permissions.MetricDefinitionsArchive,
    'Progress metrics',
    'Archive metric definitions.',
  ),
  workspace(Permissions.MeasurementsRead, 'Measurements', 'Read measurement entries.'),
  workspace(Permissions.MeasurementsCreate, 'Measurements', 'Create measurement entries.'),
  workspace(Permissions.MeasurementsUpdate, 'Measurements', 'Correct measurement entries.'),
  workspace(Permissions.ProgressPhotosRead, 'Progress photos', 'Read progress photo metadata.'),
  workspace(Permissions.ProgressPhotosCreate, 'Progress photos', 'Create progress photo metadata.'),
  workspace(
    Permissions.ProgressPhotosUpdateVisibility,
    'Progress photos',
    'Update progress photo visibility.',
  ),
  workspace(Permissions.ProgressPhotosDelete, 'Progress photos', 'Delete progress photo metadata.'),
  workspace(Permissions.HealthRead, 'Health profile', 'Read full health profile data.'),
  workspace(Permissions.HealthUpdate, 'Health profile', 'Update health profile data.'),
  workspace(
    Permissions.HealthFoodAllergiesRead,
    'Health profile',
    'Read food allergy data for nutrition service.',
  ),
  workspace(Permissions.NotesRead, 'Coaching notes', 'Read visible coaching notes.'),
  workspace(Permissions.NotesCreate, 'Coaching notes', 'Create coaching notes.'),
  workspace(Permissions.NotesUpdate, 'Coaching notes', 'Update authored coaching notes.'),
  workspace(Permissions.NotesArchive, 'Coaching notes', 'Archive authored coaching notes.'),
  workspace(Permissions.AdherenceRead, 'Adherence', 'Read adherence configuration and tracking.'),
  workspace(Permissions.AdherenceConfigure, 'Adherence', 'Configure adherence metrics.'),
  workspace(Permissions.AdherenceUpdate, 'Adherence', 'Update daily adherence tracking.'),
  workspace(Permissions.AdherenceCorrect, 'Adherence', 'Correct historical adherence tracking.'),
  workspace(Permissions.NutritionPlansRead, 'Nutrition', 'Read nutrition plans.'),
  workspace(Permissions.NutritionPlansCreate, 'Nutrition', 'Create nutrition plans.'),
  workspace(Permissions.NutritionPlansUpdate, 'Nutrition', 'Update nutrition plans.'),
  workspace(Permissions.NutritionPlansActivate, 'Nutrition', 'Activate nutrition plans.'),
  workspace(Permissions.NutritionPlansComplete, 'Nutrition', 'Complete nutrition plans.'),
  workspace(Permissions.NutritionPlansArchive, 'Nutrition', 'Archive nutrition plans.'),
  workspace(Permissions.DocumentsRead, 'Documents', 'Read documents.'),
  workspace(Permissions.MedicalDocumentsRead, 'Medical documents', 'Read medical documents.'),
  platform(Permissions.LeadsRead, 'Leads', 'Read platform leads.'),
  platform(Permissions.LeadsUpdate, 'Leads', 'Update platform leads.'),
  platform(Permissions.LeadsConvert, 'Leads', 'Convert leads into workspaces.'),
  platform(Permissions.LeadsMarkDuplicate, 'Leads', 'Mark duplicate leads.'),
  platform(Permissions.LeadsMerge, 'Leads', 'Merge duplicate leads.'),
  platform(Permissions.SupportSessionsStart, 'Support', 'Start support sessions.'),
  platform(Permissions.SystemExercisesRead, 'System exercises', 'Read system exercises.'),
  platform(Permissions.SystemExercisesCreate, 'System exercises', 'Create system exercises.'),
  platform(Permissions.SystemExercisesUpdate, 'System exercises', 'Update system exercises.'),
  platform(Permissions.SystemExercisesArchive, 'System exercises', 'Archive system exercises.'),
  platform(Permissions.SystemFoodsRead, 'System foods', 'Read system foods.'),
  platform(Permissions.SystemFoodsCreate, 'System foods', 'Create system foods.'),
  platform(Permissions.SystemFoodsUpdate, 'System foods', 'Update system foods.'),
  platform(Permissions.SystemFoodsArchive, 'System foods', 'Archive system foods.'),
];

export const permissionKeys = new Set(permissionDefinitions.map((definition) => definition.key));

export interface SystemPermissionProfileSeed {
  context: PermissionContext;
  name: string;
  roleKey: string;
  permissions: Array<{ permission: PermissionKey; effect: PermissionEffect }>;
}

export const systemPermissionProfiles: SystemPermissionProfileSeed[] = [
  {
    context: 'PLATFORM',
    name: 'Platform Super Admin',
    roleKey: 'PLATFORM_SUPER_ADMIN',
    permissions: permissionDefinitions
      .filter((definition) => definition.allowedContexts.includes('PLATFORM'))
      .map((definition) => ({ permission: definition.key as PermissionKey, effect: 'ALLOW' })),
  },
  {
    context: 'PLATFORM',
    name: 'Sales/Lead Admin',
    roleKey: 'SALES_LEAD_ADMIN',
    permissions: [
      Permissions.LeadsRead,
      Permissions.LeadsUpdate,
      Permissions.LeadsConvert,
      Permissions.LeadsMarkDuplicate,
      Permissions.LeadsMerge,
    ].map((permission) => ({ permission, effect: 'ALLOW' })),
  },
  {
    context: 'PLATFORM',
    name: 'Subscription Admin',
    roleKey: 'SUBSCRIPTION_ADMIN',
    permissions: [
      Permissions.PlansRead,
      Permissions.PlansCreate,
      Permissions.PlansUpdate,
      Permissions.PlansArchive,
      Permissions.PlansVersionsCreate,
      Permissions.SubscriptionsRead,
      Permissions.SubscriptionsStartTrial,
      Permissions.SubscriptionsChangePlan,
      Permissions.SubscriptionsChangeTerms,
      Permissions.SubscriptionsFreeze,
      Permissions.SubscriptionsReactivate,
      Permissions.SubscriptionsCancel,
      Permissions.PaymentsRead,
      Permissions.PaymentsApprove,
      Permissions.PaymentsReject,
    ].map((permission) => ({ permission, effect: 'ALLOW' })),
  },
  {
    context: 'WORKSPACE',
    name: 'Gym Owner',
    roleKey: 'GYM_OWNER',
    permissions: [
      Permissions.WorkspacesRead,
      Permissions.WorkspacesManage,
      Permissions.WorkspacesUpdate,
      Permissions.BillingSubscriptionRead,
      Permissions.BillingUsageRead,
      Permissions.BillingPaymentsRead,
      Permissions.BillingPaymentsCreate,
      Permissions.BranchesRead,
      Permissions.BranchesManage,
      Permissions.BranchesCreate,
      Permissions.BranchesUpdate,
      Permissions.BranchesArchive,
      Permissions.StaffRead,
      Permissions.StaffManage,
      Permissions.StaffInvite,
      Permissions.StaffInvitesRevoke,
      Permissions.StaffBranchesManage,
      Permissions.StaffPermissionsManage,
      Permissions.TraineesRead,
      Permissions.TraineesUpdate,
      Permissions.TraineesInvite,
      Permissions.TraineesAccept,
      Permissions.TraineesReject,
      Permissions.TraineesEnd,
      Permissions.TraineesReactivate,
      Permissions.TraineesAssignmentsPrimaryManage,
      Permissions.TraineesAssignmentsAssistantManage,
      Permissions.TraineesAssignmentsNutritionistManage,
      Permissions.TraineesMigrateOut,
      Permissions.TraineesMigrateIn,
      Permissions.ExercisesRead,
      Permissions.ExercisesCreate,
      Permissions.ExercisesUpdate,
      Permissions.ExercisesArchive,
      Permissions.ProgramsRead,
      Permissions.ProgramsCreate,
      Permissions.ProgramsUpdate,
      Permissions.ProgramsActivate,
      Permissions.ProgramsComplete,
      Permissions.ProgramsArchive,
      Permissions.ProgramTemplatesRead,
      Permissions.ProgramTemplatesCreate,
      Permissions.ProgramTemplatesUpdate,
      Permissions.ProgramTemplatesArchive,
      Permissions.WorkoutsRead,
      Permissions.WorkoutsCreate,
      Permissions.WorkoutsUpdate,
      Permissions.WorkoutsComplete,
      Permissions.WorkoutsAbandon,
      Permissions.WorkoutsCorrect,
      Permissions.WorkoutsDaySkip,
      Permissions.WorkoutsDayDefer,
      Permissions.PersonalRecordsRead,
      Permissions.MetricDefinitionsRead,
      Permissions.MetricDefinitionsCreate,
      Permissions.MetricDefinitionsUpdate,
      Permissions.MetricDefinitionsArchive,
      Permissions.MeasurementsRead,
      Permissions.AdherenceRead,
      Permissions.AdherenceConfigure,
      Permissions.FoodsRead,
      Permissions.FoodsCreate,
      Permissions.FoodsUpdate,
      Permissions.FoodsArchive,
      Permissions.NutritionPlansRead,
      Permissions.NutritionPlansCreate,
      Permissions.NutritionPlansUpdate,
      Permissions.NutritionPlansActivate,
      Permissions.NutritionPlansComplete,
      Permissions.NutritionPlansArchive,
      Permissions.DocumentsRead,
    ].map((permission) => ({ permission, effect: 'ALLOW' })),
  },
  {
    context: 'WORKSPACE',
    name: 'Gym Manager',
    roleKey: 'GYM_MANAGER',
    permissions: [
      Permissions.TraineesRead,
      Permissions.TraineesUpdate,
      Permissions.TraineesInvite,
      Permissions.TraineesAccept,
      Permissions.TraineesReject,
      Permissions.TraineesEnd,
      Permissions.TraineesReactivate,
      Permissions.TraineesAssignmentsPrimaryManage,
      Permissions.TraineesAssignmentsAssistantManage,
      Permissions.TraineesAssignmentsNutritionistManage,
      Permissions.TraineesMigrateIn,
      Permissions.ProgramsRead,
      Permissions.ProgramsUpdate,
      Permissions.WorkoutsRead,
      Permissions.PersonalRecordsRead,
      Permissions.MetricDefinitionsRead,
      Permissions.MeasurementsRead,
      Permissions.AdherenceRead,
      Permissions.AdherenceConfigure,
      Permissions.FoodsRead,
      Permissions.NutritionPlansRead,
      Permissions.NutritionPlansUpdate,
      Permissions.DocumentsRead,
    ].map((permission) => ({ permission, effect: 'ALLOW' })),
  },
  {
    context: 'WORKSPACE',
    name: 'Trainer',
    roleKey: 'TRAINER',
    permissions: [
      Permissions.TraineesRead,
      Permissions.TraineesUpdate,
      Permissions.TraineesInvite,
      Permissions.TraineesAccept,
      Permissions.TraineesReject,
      Permissions.TraineesEnd,
      Permissions.TraineesReactivate,
      Permissions.TraineesAssignmentsPrimaryManage,
      Permissions.TraineesAssignmentsAssistantManage,
      Permissions.TraineesAssignmentsNutritionistManage,
      Permissions.TraineesMigrateOut,
      Permissions.ExercisesRead,
      Permissions.ExercisesCreate,
      Permissions.ExercisesUpdate,
      Permissions.ExercisesArchive,
      Permissions.ProgramsRead,
      Permissions.ProgramsCreate,
      Permissions.ProgramsUpdate,
      Permissions.ProgramsActivate,
      Permissions.ProgramsComplete,
      Permissions.ProgramsArchive,
      Permissions.ProgramTemplatesRead,
      Permissions.ProgramTemplatesCreate,
      Permissions.ProgramTemplatesUpdate,
      Permissions.ProgramTemplatesArchive,
      Permissions.WorkoutsRead,
      Permissions.WorkoutsCreate,
      Permissions.WorkoutsUpdate,
      Permissions.WorkoutsComplete,
      Permissions.WorkoutsAbandon,
      Permissions.WorkoutsCorrect,
      Permissions.WorkoutsDaySkip,
      Permissions.WorkoutsDayDefer,
      Permissions.PersonalRecordsRead,
      Permissions.MeasurementsRead,
      Permissions.MeasurementsCreate,
      Permissions.ProgressPhotosRead,
      Permissions.HealthRead,
      Permissions.NotesRead,
      Permissions.NotesCreate,
      Permissions.NotesUpdate,
      Permissions.NotesArchive,
      Permissions.AdherenceRead,
      Permissions.AdherenceConfigure,
      Permissions.AdherenceUpdate,
      Permissions.AdherenceCorrect,
      Permissions.FoodsRead,
      Permissions.NutritionPlansRead,
      Permissions.NutritionPlansUpdate,
      Permissions.DocumentsRead,
    ].map((permission) => ({ permission, effect: 'ALLOW' })),
  },
  {
    context: 'WORKSPACE',
    name: 'Trainee',
    roleKey: 'TRAINEE',
    permissions: [
      Permissions.TraineesRead,
      Permissions.ProgramsRead,
      Permissions.WorkoutsRead,
      Permissions.WorkoutsCreate,
      Permissions.WorkoutsUpdate,
      Permissions.WorkoutsComplete,
      Permissions.WorkoutsAbandon,
      Permissions.WorkoutsDaySkip,
      Permissions.WorkoutsDayDefer,
      Permissions.PersonalRecordsRead,
      Permissions.MeasurementsRead,
      Permissions.MeasurementsCreate,
      Permissions.MeasurementsUpdate,
      Permissions.ProgressPhotosRead,
      Permissions.HealthRead,
      Permissions.HealthUpdate,
      Permissions.NotesRead,
      Permissions.AdherenceRead,
      Permissions.AdherenceUpdate,
      Permissions.NutritionPlansRead,
      Permissions.DocumentsRead,
    ].map((permission) => ({ permission, effect: 'ALLOW' })),
  },
  {
    context: 'WORKSPACE',
    name: 'Assistant Trainer',
    roleKey: 'ASSISTANT_TRAINER',
    permissions: [
      Permissions.TraineesRead,
      Permissions.ProgramsRead,
      Permissions.WorkoutsRead,
      Permissions.WorkoutsCreate,
      Permissions.MeasurementsRead,
      Permissions.ProgressPhotosRead,
      Permissions.AdherenceRead,
      Permissions.DocumentsRead,
    ].map((permission) => ({ permission, effect: 'ALLOW' })),
  },
  {
    context: 'WORKSPACE',
    name: 'Nutritionist',
    roleKey: 'NUTRITIONIST',
    permissions: [
      Permissions.TraineesRead,
      Permissions.FoodsRead,
      Permissions.FoodsCreate,
      Permissions.FoodsUpdate,
      Permissions.FoodsArchive,
      Permissions.NutritionPlansRead,
      Permissions.NutritionPlansCreate,
      Permissions.NutritionPlansUpdate,
      Permissions.NutritionPlansActivate,
      Permissions.NutritionPlansComplete,
      Permissions.NutritionPlansArchive,
      Permissions.HealthFoodAllergiesRead,
      Permissions.AdherenceRead,
    ].map((permission) => ({ permission, effect: 'ALLOW' })),
  },
];

function platform(
  key: PermissionKey,
  displayName: string,
  description: string,
): PermissionDefinition {
  return {
    key,
    category: key.split('.')[0] ?? key,
    module: 'platform',
    displayName,
    description,
    allowedScopes: ['WORKSPACE'],
    allowedContexts: ['PLATFORM'],
    system: true,
  };
}

function workspace(
  key: PermissionKey,
  displayName: string,
  description: string,
): PermissionDefinition {
  return {
    key,
    category: key.split('.')[0] ?? key,
    module: 'workspace',
    displayName,
    description,
    allowedScopes: workspaceScopes,
    allowedContexts: ['WORKSPACE'],
    system: true,
  };
}
